version: "3.9"
services:
  server:
    image: docker.io/${DOCKERHUB_USERNAME}/lab04-server:${TAG:-latest}
    container_name: lab04-server
    environment:
      - PORT=4000
    ports:
      - "4000:4000"
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://localhost:4000/api/users >/dev/null || exit 1"]
      interval: 10s
      timeout: 3s
      retries: 10
  client:
    image: docker.io/${DOCKERHUB_USERNAME}/lab04-client:${TAG:-latest}
    container_name: lab04-client
    depends_on:
      server:
        condition: service_healthy
    ports:
      - "8080:80"
    restart: unless-stopped
