name: lab04 Client CI

on:
  pull_request:
    branches: [ master ]
    paths:
      - 'lab04/src/client/**'

env:
  IMAGE_NAME: lab04-client
  CONTEXT_PATH: lab04/src/client

concurrency:
  group: lab04-client-${{ github.ref }}
  cancel-in-progress: false

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Lint Dockerfile
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: ${{ env.CONTEXT_PATH }}/Dockerfile

  build:
    name: build
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: actions/checkout@v4
      - name: Setup QEMU
        uses: docker/setup-qemu-action@v3
      - name: Setup Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build Docker image
        uses: docker/build-push-action@v6
        with:
          context: ${{ env.CONTEXT_PATH }}
          file: ${{ env.CONTEXT_PATH }}/Dockerfile
          tags: ${{ env.IMAGE_NAME }}:ci
          push: false
          load: true
      - name: Save image as artifact
        run: docker save ${{ env.IMAGE_NAME }}:ci -o ${{ env.IMAGE_NAME }}.tar
      - name: Upload image artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.IMAGE_NAME }}-image
          path: ${{ env.IMAGE_NAME }}.tar

  test:
    name: test
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download image artifact
        uses: actions/download-artifact@v4
        with:
          name: lab04-client-image
          path: .

      - name: Load Docker image
        run: docker load -i lab04-client.tar

      - name: Run container and wait until ready
        run: |
          docker run -d --rm -p 8080:80 --name lab04-client lab04-client:ci

          echo "⏳ Waiting for container to become ready..."
          for i in {1..30}; do
            if curl -fsS http://127.0.0.1:8080 >/dev/null; then
              echo "✅ Client is up!"
              exit 0
            fi
            sleep 1
          done

          echo "❌ Client failed to start within 30s"
          echo "---- docker ps ----"
          docker ps -a || true
          echo "---- docker logs ----"
          docker logs lab04-client || true
          exit 1


        